### ISSUE TITLE
Больше проверок для VisicosTest

### ISSUE THREAD

**Issue by blockin90** [KeshaTheRaven/Lab7#2]
тесты должны покрывать все граничные значения, сейчас же проверяется только один из возможных високосных годов (по заданию их сильно больше: Високосным считается год, делящийся на 4, за исключением тех годов, которые делятся на 100 и не делятся на 400 (например, годы 300, 1300, и 1900 не являются високосными, а 1200 и 2000 – являются).

Чтобы при этом не плодить копипастой один код, можно написать, т.н. data driven test:
https://learn.microsoft.com/en-us/visualstudio/test/how-to-create-a-data-driven-unit-test?view=vs-2022

**Comment by KeshaTheRaven** [comment]
Seemed like fixed
